/**
 * Bundles the config and the prompts into a module the Worker can import.
 *
 * A Worker has no readable filesystem at runtime, so everything it needs has to
 * be in the deployed code. This runs at build time (`npm run build`, which
 * Cloudflare runs before every deploy) and writes one generated module.
 *
 * The generated file is not committed. Its content is entirely derived from
 * `platform.config.yaml` (or the example, when the licensee has not written one
 * yet) and `prompts/*.md`, so committing it would give the repository two
 * answers to "what is this account configured as".
 *
 * **Whether the licensee has configured anything is recorded here too.** With
 * no config of their own, the Worker boots on the example and serves the setup
 * screen rather than running a stranger's example account.
 */

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "worker", "bundled.generated.ts");

// The same names `resolveConfigPath` accepts. A licensee who wrote JSON is
// configured, and must not be told they are not.
const CONFIG_NAMES = ["platform.config.yaml", "platform.config.yml", "platform.config.json"];

async function main(): Promise<number> {
  const own = CONFIG_NAMES.map((name) => join(ROOT, name)).find((path) => existsSync(path));
  const configPath = own ?? join(ROOT, "platform.config.example.yaml");
  const configText = await readFile(configPath, "utf8");

  const promptsDir = join(ROOT, "prompts");
  const names = (await readdir(promptsDir)).filter((name) => name.endsWith(".md")).sort();
  const prompts: Record<string, string> = {};
  for (const name of names) {
    prompts[name.slice(0, -3)] = await readFile(join(promptsDir, name), "utf8");
  }

  const body = `// Generated by scripts/bundle-worker.ts. Do not edit, do not commit.
// Source: ${own ? "the licensee's own config" : "platform.config.example.yaml (not configured yet)"}

// Widened on purpose: the value differs between builds, and code that reads it
// has to compile for both.
export const configSource: "licensee" | "example" = ${JSON.stringify(own ? "licensee" : "example")};
export const configText = ${JSON.stringify(configText)};
export const prompts: Readonly<Record<string, string>> = ${JSON.stringify(prompts, null, 2)};
`;

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, body, "utf8");
  process.stdout.write(
    `bundled ${own ? "your config" : "the example config"} and ${names.length} prompts into src/worker/bundled.generated.ts\n`,
  );
  return 0;
}

process.exitCode = await main();
