#!/usr/bin/env node
/**
 * Deploys the Worker, keeping our own D1 database id out of the repository.
 *
 * `wrangler.jsonc` ships to licensees, and its `database_id` is a placeholder
 * that the Deploy to Cloudflare button rewrites when it provisions a database
 * in the licensee's own account. A hand-run `wrangler deploy` gets no such
 * rewrite: it needs a real id, and writing ours into the shipped file would
 * hand every licensee a pointer at our database.
 *
 * So the id lives in `.env.local` as AMP_D1_DATABASE_ID, and this script writes
 * a git-ignored copy of the config with the placeholder substituted. Set the
 * variable and you deploy against your own database; leave it unset — which is
 * every licensee — and this is a plain `wrangler deploy`, unchanged.
 *
 * Usage: npm run deploy [-- <extra wrangler flags>]
 */

import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { loadDotEnv } from "../src/config/load.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "wrangler.jsonc");
const GENERATED = join(ROOT, "wrangler.generated.jsonc");
const PLACEHOLDER = "placeholder-replaced-on-first-deploy";

async function configFor(databaseId: string | undefined): Promise<string> {
  if (!databaseId) return SOURCE;

  const text = await readFile(SOURCE, "utf8");
  if (!text.includes(PLACEHOLDER)) {
    // Either someone pasted a real id into the shipped file - which is the
    // thing this script exists to prevent - or the placeholder was renamed.
    throw new Error(
      `wrangler.jsonc no longer contains "${PLACEHOLDER}". If a real database id was ` +
        `written into it, take it back out: it ships to licensees. Otherwise update ` +
        `PLACEHOLDER in scripts/deploy-worker.ts.`,
    );
  }

  await writeFile(
    GENERATED,
    `// Generated by scripts/deploy-worker.ts from wrangler.jsonc. Not committed.\n` +
      `// Edit wrangler.jsonc; this file is overwritten on every deploy.\n` +
      text.replace(PLACEHOLDER, databaseId),
    "utf8",
  );
  return GENERATED;
}

async function main(argv: readonly string[]): Promise<number> {
  loadDotEnv();
  const databaseId = process.env["AMP_D1_DATABASE_ID"];
  const config = await configFor(databaseId);

  process.stdout.write(
    databaseId
      ? `Deploying against the D1 database in AMP_D1_DATABASE_ID (${config.slice(ROOT.length + 1)}).\n`
      : `Deploying with wrangler.jsonc as it ships. Set AMP_D1_DATABASE_ID in .env.local to ` +
          `point at a database you created yourself.\n`,
  );

  const result = spawnSync(
    "npx",
    ["wrangler", "deploy", "--config", config, ...argv],
    { stdio: "inherit", cwd: ROOT },
  );
  return result.status ?? 1;
}

process.exitCode = await main(process.argv.slice(2));
